### ISSUE TITLE
Request to take over maintenance

### ISSUE THREAD

**Issue by gh2k** [hipsnip-cookbooks/papertrail-rsyslog#6]
README.md says this cookbook is abandoned. Any chance I can pick it up? We're using papertrail+syslog for our stuff and I'd be happy to keep this going.

**Comment by motns** [comment]
Hello, and sorry for the delay!
Yes, I'd be more than happy to hand this over to you. Just let me know what your username is on Chef Supermarket, and I'll transfer ownership; then you can push new version there directly. I'll also update the README here to point people at your GitHub repo.

One thing to point out is that currently the tests for this cookbook are broken, due to some outdated dependency versions. Also, the way we set up our cookbooks is that shared dependencies (like testing frameworks and some Rake tasks) were moved to a Gem called [cookbook-development](https://github.com/hipsnip-cookbooks/cookbook-development) - you'll probably want to stop depending on that going forward. I've made some notes about this on a PR for another one of our cookbooks, just for reference:
https://github.com/hipsnip-cookbooks/logentries-rsyslog/pull/1

**Comment by gh2k** [comment]
Thanks. I'm 'sdetheridge' on Chef Supermarket

I'll have a look at the pending PRs and see if I can get the tests working and up to date.

**Comment by motns** [comment]
Alright, I've initiated the transfer on Chef Supermarket. I have also updated the README here to point to your repo.
I'll close this issue for now, but if you have any questions about the cookbook or the tests, or if the transfer for some reason doesn't work, just re-open it.

Thanks,
Adam
